import{test}from'node:test';import assert from'node:assert/strict';import{parseSiri}from'../server/providers/buses';import{railTime,estimateBoard}from'../server/providers/trains';import{RailNetwork}from'../server/rail-network';import{Poller}from'../server/poller';import{parseTraffic}from'../server/providers/traffic';
test('normalises SIRI XML without namespaces leaking into the model',()=>{const xml='<Siri><ServiceDelivery><VehicleMonitoringDelivery><VehicleActivity><RecordedAtTime>2026-09-05T08:00:00Z</RecordedAtTime><MonitoredVehicleJourney><VehicleRef>701</VehicleRef><OperatorRef>RGB</OperatorRef><PublishedLineName>17</PublishedLineName><VehicleLocation><Longitude>-0.97</Longitude><Latitude>51.455</Latitude></VehicleLocation></MonitoredVehicleJourney></VehicleActivity></VehicleMonitoringDelivery></ServiceDelivery></Siri>';const out=parseSiri(xml);assert.equal(out.length,1);assert.equal(out[0].id,'bods:RGB:701');assert.equal(out[0].label,'17');assert.deepEqual(out[0].position,[-.97,51.455]);});
test('rail times resolve BST and midnight',()=>{const time=railTime('10:00',Date.parse('2026-07-05T08:30:00Z'));assert.equal(new Date(time!).toISOString(),'2026-07-05T09:00:00.000Z');assert.equal(new Date(railTime('00:03',Date.parse('2026-09-05T22:58:00Z'))!).toISOString(),'2026-09-05T23:03:00.000Z');assert.equal(railTime('Delayed',Date.now()),null);});
test('rail geometry follows connected tracks',()=>{const rail=new RailNetwork([{properties:{railway:'rail'},geometry:{type:'LineString',coordinates:[[-.9723182,51.4592197],[-.981,51.457],[-.9907169,51.4546483]]}}]);assert.equal(rail.route('RDG','RDW')?.length,3);assert.equal(rail.route('RDG','TWY'),null);});
test('cancelled train is emitted as cancellation, never estimated movement',()=>{const out=estimateBoard({generatedAt:'2026-09-05T08:00:00Z',trainServices:{service:{serviceID:'one',isCancelled:'true'}}},'RDG',new RailNetwork([]));assert.equal(out.observations[0].cancelled,true);});
test('poller serialises requests and exposes recovery',async()=>{let calls=0,release:()=>void=()=>{};const p=new Poller('buses','Buses',15000,async()=>{calls++;await new Promise<void>(r=>release=r);return[1];},'');const pending=p.tick();await p.tick();assert.equal(calls,1);release();await pending;assert.equal(p.health().state,'live');p.stop();const f=new Poller('traffic','Traffic',60000,async()=>{throw Error('token=secret');},'');await f.tick();assert.equal(f.health().state,'unavailable');assert.ok(!f.health().message.includes('secret'));f.stop();});
test('traffic validates observed metrics instead of deriving them from speed limits',()=>{assert.throws(()=>parseTraffic([{id:'x',currentSpeed:30}]));assert.deepEqual(parseTraffic([]),[]);});
test('timed calls produce a labelled train estimate on the railway',()=>{const rail=new RailNetwork([{properties:{railway:'rail'},geometry:{type:'LineString',coordinates:[[-.9723182,51.4592197],[-.981,51.457],[-.9907169,51.4546483]]}}]);const now=Date.parse('2026-09-05T08:05:00Z');const board={generatedAt:new Date(now).toISOString(),trainServices:{service:{serviceID:'test',std:'09:00',etd:'On time',operator:'GWR',subsequentCallingPoints:{callingPointList:{callingPoint:{crs:'RDW',st:'09:10',et:'On time'}}}}}};const out=estimateBoard(board,'RDG',rail,now);assert.equal(out.observations.length,1);assert.equal(out.observations[0].status,'estimated');assert.ok(out.observations[0].position[0]<-.9723182);assert.ok(out.observations[0].position[0]>-.9907169);});
test('station arrival/departure window takes precedence over approach interpolation',()=>{const now=Date.parse('2026-09-05T08:06:00Z'),board={generatedAt:new Date(now).toISOString(),trainServices:{service:{serviceID:'hold',sta:'09:05',std:'09:10',eta:'On time',etd:'On time'}}};const out=estimateBoard(board,'RDG',new RailNetwork([]),now);assert.equal(out.observations[0].stopUntil,'2026-09-05T08:10:00.000Z');});
