export const icons={layers:'▱',bus:'▰',train:'▥',roadworks:'△',traffic:'≋',signs:'◉',cameras:'▣',buildings:'▥'};
export function shell(){document.querySelector('#app')!.innerHTML=`
<main id="map" aria-label="Interactive 3D map of Reading"></main>
<header class="topbar"><a class="brand" href="/" aria-label="Mini Reading home"><span class="brand-mark">r<span>3</span></span><span>mini <strong>reading</strong><small>A TOWN IN THREE DIMENSIONS</small></span></a><div class="top-divider"></div><span class="area-label">Berkshire, England</span><button id="data-button" class="status-button"><span class="status-dot"></span><span id="overall-status">Checking feeds</span><span>↗</span></button></header>
<aside class="explore-panel" aria-label="Map controls"><div class="search-wrap"><span>⌕</span><input id="search" type="search" placeholder="Find a place in Reading" aria-label="Search Reading places" autocomplete="off"></div><div id="search-results" class="search-results" hidden></div><div class="panel-heading"><span>EXPLORE READING</span><button id="collapse-layers" aria-label="Toggle map layers" aria-expanded="true">−</button></div><div id="layers"><div class="layer-title">The miniature</div><label class="layer-row"><span><i>▥</i>3D buildings</span><input type="checkbox" data-layer="buildings" checked role="switch"></label><div class="layer-title">On the move</div>${[['buses','▰','Live buses'],['trains','▥','Live trains'],['traffic','≋','Traffic congestion'],['roadworks','△','Roadworks & closures']].map(([id,icon,label])=>`<label class="layer-row"><span><i>${icon}</i>${label}<small id="count-${id}">—</small></span><input type="checkbox" data-layer="${id}" checked role="switch"></label>`).join('')}<div class="layer-title">Along the road</div><label class="layer-row"><span><i>◉</i>Speed limits</span><input type="checkbox" data-layer="signs" checked role="switch"></label><label class="layer-row"><span><i>▣</i>Cameras</span><input type="checkbox" data-layer="cameras" checked role="switch"></label></div><div class="panel-foot"><span class="small-dot"></span><span id="geography-status">Loading Reading’s geography…</span></div></aside>
<div id="traffic-legend" class="traffic-legend">Traffic congestion <span class="traffic-scale"></span><small>Slow → Fast · <span id="traffic-availability">Checking feed</span></small></div><div class="places-dock" aria-label="Landmarks"><span class="dock-label">TAKE A CLOSER LOOK</span><div id="landmark-buttons"></div></div>
<div class="map-tools"><button id="home-view" title="Return to Reading station" aria-label="Reset view">⌂</button><button id="overview" title="Show greater Reading" aria-label="Show whole map">⤢</button><button id="tilt-view" title="Toggle 2D and 3D view" aria-label="Toggle 2D and 3D view">3D</button><button id="orbit-view" title="Orbit Reading" aria-label="Orbit Reading" aria-pressed="false">↻</button></div>
<div class="view-caption"><span class="eyebrow">READING STATION</span><span id="view-coordinates">51.4584° N · 0.9717° W</span></div>
<div class="bottom-note"><span>Drag to explore</span><span>Right-drag to tilt</span><span>Scroll to zoom</span></div>
<div id="toast" role="status" hidden></div><div id="pick-bar" class="pick-bar" role="status" hidden><span id="pick-text"></span><button id="pick-cancel" type="button">Cancel</button></div><aside id="details" class="details-panel" aria-label="Map details" tabindex="-1" hidden><button id="sheet-handle" class="sheet-handle" aria-label="Show more of the panel" aria-expanded="false"></button><button id="close-details" class="close-button" aria-label="Close details">×</button><div id="details-content"></div></aside>
<div id="loading" class="loading"><span class="loader"></span><strong>Building your little Reading</strong><span>Real streets. A different perspective.</span></div>
`;
 if(phone()){const toggle=document.querySelector('#collapse-layers')!;toggle.textContent='+';toggle.setAttribute('aria-expanded','false');}
 document.querySelector('#close-details')!.addEventListener('click',()=>{document.querySelector<HTMLElement>('#details')!.hidden=true;});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&cancelPick){cancelPick();return;}if(e.key==='Escape'){document.querySelector<HTMLElement>('#details')!.hidden=true;document.querySelector<HTMLElement>('#search-results')!.hidden=true;}});
 document.querySelector('#collapse-layers')!.addEventListener('click',e=>{const el=document.querySelector<HTMLElement>('#layers')!,panel=document.querySelector('.explore-panel')!,b=e.currentTarget as HTMLElement;if(phone()){const open=panel.classList.toggle('mobile-open');el.hidden=false;if(open)document.querySelector<HTMLElement>('#details')!.hidden=true;b.textContent=open?'−':'+';b.setAttribute('aria-expanded',String(open));}else{el.hidden=!el.hidden;b.textContent=el.hidden?'+':'−';b.setAttribute('aria-expanded',String(!el.hidden));}});
 document.querySelector('#sheet-handle')!.addEventListener('click',e=>{const open=document.querySelector('#details')!.classList.toggle('expanded'),b=e.currentTarget as HTMLElement;b.setAttribute('aria-expanded',String(open));b.setAttribute('aria-label',open?'Show less of the panel':'Show more of the panel');});
 document.querySelector('#pick-cancel')!.addEventListener('click',()=>cancelPick?.());
}
/** Phones get the details panel as a bottom sheet and the layers as a pull-down; only one is open at a time. */
const phone=()=>matchMedia('(max-width:680px)').matches;
function closeLayersSheet(){const panel=document.querySelector('.explore-panel')!;if(!panel.classList.contains('mobile-open'))return;panel.classList.remove('mobile-open');const b=document.querySelector('#collapse-layers')!;b.textContent='+';b.setAttribute('aria-expanded','false');}
export function escape(s:unknown){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export function detail(html:string){document.querySelector('#details-content')!.innerHTML=html;const el=document.querySelector<HTMLElement>('#details')!;if(phone())closeLayersSheet();el.hidden=false;el.focus({preventScroll:true});}
export function toast(text:string){const el=document.querySelector<HTMLElement>('#toast')!;el.textContent=text;el.hidden=false;setTimeout(()=>el.hidden=true,4500);}
let cancelPick:(()=>void)|null=null;
/** Hides the panels while the next map tap picks a point, with a bar that says what to tap. Returns the function to call once the tap arrives; Cancel or Escape calls `cancel` instead. */
export function startPick(text:string,cancel:()=>void){
 const bar=document.querySelector<HTMLElement>('#pick-bar')!;document.querySelector('#pick-text')!.textContent=text;bar.hidden=false;document.body.classList.add('picking');closeLayersSheet();
 const done=()=>{bar.hidden=true;document.body.classList.remove('picking');cancelPick=null;};
 cancelPick=()=>{cancel();done();};return done;
}
