import {CADENCE} from '../../shared/feed-policy';
import{Marker,type Map,type GeoJSONSource}from'maplibre-gl';import type{ReadingScene}from'../scene/layer';import type{StaticFeatures,GeographyManifest,FeedStatus,VehicleObservation,RoadEvent,TrafficSegment,LngLat}from'../../shared/types';import{detail,escape,toast}from'../ui/shell';import{VehicleTracker}from'../movement/tracker';import{VehicleMeshes}from'../scene/vehicles';import{RoadFurniture}from'../scene/road-furniture';import{eventDuration,formatDate}from'../../shared/road-events';import{registerMapTools}from'../ui/webmcp';
export async function connectLayers(map:Map,scene:ReadingScene,features:StaticFeatures,manifest:GeographyManifest){const state:Record<string,boolean>={buildings:true,buses:true,trains:true,traffic:true,roadworks:true,signs:true,cameras:true};const tracker=new VehicleTracker(),vehicles=new VehicleMeshes(),furniture=new RoadFurniture(features);scene.extras.add(vehicles.group,furniture.group);let selectedBusRoute='';let poses=tracker.poses(),feeds:FeedStatus[]=[],events:RoadEvent[]=[],roadTraffic:TrafficSegment[]=[],routes:Record<string,LngLat[]>={},disposed=false,lastMarkers=0,timer:ReturnType<typeof setTimeout>;const markers=new globalThis.Map<string,Marker>();let vehicleTimer:ReturnType<typeof setInterval>;
 const healthDetail=()=>detail(`<span class="pill">Source & freshness</span><h2>Reading, with context</h2><p>Vehicle positions are shown only when source observations are available. Train positions are estimates.</p>${feeds.map(f=>`<section class="feed-card"><strong>${escape(f.label)}</strong> <span class="pill">${escape(f.state)}</span><p>${escape(f.message)}</p><small>${f.lastSuccess?'Last update '+escape(formatDate(f.lastSuccess)):'No observations received'}</small></section>`).join('')}<section class="feed-card"><strong>The map</strong><p>${manifest.stats.buildings.toLocaleString()} building footprints · ${features.cameras.length} mapped cameras. Most heights and all landmark architecture are approximate.</p><small>OSM snapshot ${escape(formatDate(manifest.sourceTimestamp,true))}</small></section><p>Dashed speed badges describe a road’s mapped limit. Solid badges mark mapped sign locations. Camera locations do not establish current operation.</p><p><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors · ODbL</a><br>Bus route geometry: Reading Buses · OGL 3.0</p><div class="legend"><span></span>Traffic: amber = slower, red = heavily delayed</div>`);
 document.querySelector('#data-button')!.addEventListener('click',healthDetail);
 const roadDetail=(e:RoadEvent)=>{const d=eventDuration(e);detail(`<span class="pill">${e.kind==='closure'?'Road closure':'Roadworks'} · ${escape(e.status)}</span><h2>${escape(e.title)}</h2><p>${escape(e.description)}</p><dl><dt>Organisation</dt><dd>${escape(e.organisation)}</dd><dt>Traffic management</dt><dd>${escape(e.trafficManagement??'Unknown')}</dd><dt>Planned start</dt><dd>${escape(formatDate(e.plannedStart,e.datePrecision==='date'))}</dd><dt>Planned end</dt><dd>${escape(formatDate(e.plannedEnd,e.datePrecision==='date'))}</dd><dt>Actual start</dt><dd>${escape(formatDate(e.actualStart))}</dd><dt>Actual end</dt><dd>${escape(formatDate(e.actualEnd))}</dd><dt>${e.actualStart&&e.actualEnd?'Actual duration':'Expected duration'}</dt><dd>${d===null?'Unknown':d>=86400000?`${Math.round(d/86400000*10)/10} days`:`${Math.round(d/3600000*10)/10} hours`}</dd><dt>Source</dt><dd>${escape(e.source)}</dd><dt>Last updated</dt><dd>${escape(formatDate(e.observedAt))}</dd></dl>${e.geometry.type==='Point'?'<p>Only a point location is supplied. The affected road length is unknown.</p>':''}`);};
 const syncMarkers=()=>{if(disposed)return;const signCells=new Set<string>();const wanted=new Set<string>(),bounds=map.getBounds(),zoom=map.getZoom();const add=(id:string,p:LngLat,cls:string,text:string,label:string,click:()=>void)=>{if(!bounds.contains(p)||wanted.size>=160)return;if(id.startsWith('sign:')){const q=map.project(p),cell=`${Math.floor(q.x/32)}:${Math.floor(q.y/32)}`;if(signCells.has(cell))return;signCells.add(cell);}wanted.add(id);if(markers.has(id))return;const el=document.createElement('button');el.className=cls;el.textContent=text;el.setAttribute('aria-label',label);el.title=label;el.addEventListener('click',click);markers.set(id,new Marker({element:el}).setLngLat(p).addTo(map));};
  if(state.roadworks)for(const e of events)add(e.id,e.geometry.type==='Point'?e.geometry.coordinates:e.geometry.coordinates[0],`event-pin ${e.kind}`,e.kind==='closure'?'×':'△',e.title,()=>roadDetail(e));
  if(state.signs&&zoom>=15.7)for(const s of features.signs)add(`sign:${s.id}`,s.position,`sign-badge ${s.placement} ${s.limit==='NSL'?'nsl':''}`,s.limit==='NSL'?'╱':s.limit,`${s.limit} ${s.placement==='surveyed'?'sign':'road limit'}`,()=>detail(`<span class="pill">${s.placement==='surveyed'?'Mapped sign':'Mapped road limit'}</span><h2>${s.limit==='NSL'?'National speed limit':escape(s.limit)+' mph'}</h2><p>${s.placement==='surveyed'?'A sign location recorded in OpenStreetMap.':'This badge describes the mapped road limit; it is not a surveyed sign location.'}</p><dl><dt>Road</dt><dd>${escape(s.road??'Not named')}</dd><dt>Source</dt><dd>${escape(s.source)}</dd><dt>Snapshot</dt><dd>${escape(formatDate(s.observedAt,true))}</dd></dl>`));
  if(state.cameras&&zoom>=15)for(const c of features.cameras)add(`camera:${c.id}`,c.position,'camera-pin','▣',`${c.kind} camera`,()=>detail(`<span class="pill">Mapped camera</span><h2>${c.kind==='red-light'?'Red-light camera':'Speed camera'}</h2><p>Location from OpenStreetMap. Camera operation and enforcement status are not known.</p><dl><dt>Source</dt><dd>${escape(c.source)}</dd><dt>Snapshot</dt><dd>${escape(formatDate(c.observedAt,true))}</dd></dl>`));
  for(const[id,m]of markers)if(!wanted.has(id)){m.remove();markers.delete(id);}furniture.signs.visible=state.signs&&zoom>=16;furniture.cameras.visible=state.cameras&&zoom>=15;furniture.works.visible=state.roadworks;map.triggerRepaint();
 };
 map.addSource('road-events',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'road-event-lines',type:'line',source:'road-events',filter:['==',['geometry-type'],'LineString'],paint:{'line-color':['match',['get','kind'],'closure','#af6255','#bb904c'],'line-width':5,'line-opacity':.8,'line-dasharray':[1,1]}},'reading-3d');
 map.addSource('traffic',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'traffic-lines',type:'line',source:'traffic',paint:{'line-color':['step',['get','ratio'],'#ac5d53',.4,'#b9974d',.75,'#839783'],'line-width':4,'line-opacity':.8}},'road-event-lines');
 map.on('click','road-event-lines',e=>{const event=events.find(x=>x.id===e.features?.[0]?.properties.id);if(event)roadDetail(event);});map.on('click','traffic-lines',e=>{const t=roadTraffic.find(x=>x.id===e.features?.[0]?.properties.id);if(t)detail(`<span class="pill">Road traffic</span><h2>${Math.round(t.currentSpeed)} mph</h2><dl><dt>Typical free-flow speed</dt><dd>${Math.round(t.freeFlowSpeed)} mph</dd><dt>Source confidence</dt><dd>${Math.round(t.confidence*100)}%</dd><dt>Source</dt><dd>${escape(t.source)}</dd><dt>Observed</dt><dd>${escape(formatDate(t.observedAt))}</dd></dl>`);});
 map.addSource('bus-observations',{type:'geojson',data:{type:'FeatureCollection',features:[]}});
 map.addLayer({id:'bus-dots',type:'circle',source:'bus-observations',paint:{'circle-radius':['interpolate',['linear'],['zoom'],11,3,16,4],'circle-color':['get','colour'],'circle-stroke-color':'#fffdf5','circle-stroke-width':1.5}});
 map.addLayer({id:'bus-line-labels',type:'symbol',source:'bus-observations',minzoom:13,layout:{'text-field':['get','label'],'text-font':['Noto Sans Regular'],'text-size':11,'text-offset':[0,1.1]},paint:{'text-color':['get','colour'],'text-halo-color':'#fffdf5','text-halo-width':2}});
 let busSignature='';
 const syncBuses=()=>{if(disposed)return;const data:GeoJSON.FeatureCollection={type:'FeatureCollection',features:tracker.poses().filter(p=>state.buses&&p.observation.kind==='bus'&&(!selectedBusRoute||p.observation.routeGroupId===selectedBusRoute)).map(p=>({type:'Feature',geometry:{type:'Point',coordinates:p.position},properties:{id:p.observation.id,label:p.observation.label,colour:p.stale?'#87938b':p.observation.routeColour??'#527b70'}}))};const signature=JSON.stringify(data);if(signature!==busSignature){busSignature=signature;(map.getSource('bus-observations') as GeoJSONSource).setData(data);}};
 const setLayer=(id:string,value:boolean)=>{if(!(id in state))throw Error('Unknown layer');state[id]=value;document.querySelector<HTMLElement>('#traffic-legend')!.hidden=!state.traffic;document.querySelector<HTMLInputElement>(`[data-layer=${id}]`)!.checked=value;scene.setEnabled(state.buildings);map.setLayoutProperty('building-overview','visibility',state.buildings?'visible':'none');vehicles.enabled.bus=state.buses;vehicles.enabled.train=state.trains;syncBuses();map.setLayoutProperty('road-event-lines','visibility',state.roadworks?'visible':'none');map.setLayoutProperty('traffic-lines','visibility',state.traffic?'visible':'none');syncMarkers();map.triggerRepaint();};
 for(const input of document.querySelectorAll<HTMLInputElement>('[data-layer]'))input.addEventListener('change',()=>{setLayer(input.dataset.layer!,input.checked);if(input.checked){const feed=feeds.find(f=>f.id===input.dataset.layer);if(feed&&feed.state==='unavailable')toast(feed.message);}});
 scene.animate=()=>{poses=tracker.poses().filter(p=>p.observation.kind!=='bus'||!selectedBusRoute||p.observation.routeGroupId===selectedBusRoute);vehicles.update(poses,map.getZoom());return poses.length>0;};
 map.on('click',e=>{let closest=20,best:typeof poses[number]|undefined;for(const p of poses){if(!(p.observation.kind==='bus'?state.buses:state.trains))continue;const s=map.project(p.position),d=Math.hypot(s.x-e.point.x,s.y-e.point.y);if(d<closest){closest=d;best=p;}}if(best){const o=best.observation;detail(`<span class="pill">${o.kind==='bus'?'Bus':'Train'} · ${best.stale?'stale':o.status==='estimated'?'estimated position':'live observation'}</span><h2>${escape(o.label)}</h2><p>${escape(o.destination??'')}</p><dl>${o.kind==='bus'?`<dt>Route match</dt><dd>${escape(o.routeGroupId??'Unmatched; showing reported position')}</dd>`:''}<dt>Source</dt><dd>${escape(o.source)}</dd><dt>Observed</dt><dd>${escape(formatDate(o.observedAt))}</dd></dl>${o.routeGroupId?'<button id=show-bus-line class=status-button>Show bus line</button>':''}${o.kind==='train'?'<p>Position interpolated along the railway between timed calling points.</p>':''}`);document.querySelector('#show-bus-line')?.addEventListener('click',()=>document.dispatchEvent(new CustomEvent('reading-show-bus-route',{detail:o.routeGroupId})));}});
 async function get(url:string){const r=await fetch(url,{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('API unavailable');return r.json();}
 let slowUpdated=0,refreshing=false;
 const refresh=async()=>{
  if(disposed||document.hidden||refreshing)return;refreshing=true;clearTimeout(timer);
  const jobs:Promise<void>[]=[];
  jobs.push(get('/api/v1/vehicle-state').then(v=>{if(disposed)return;routes=v.routes;tracker.ingest(v.data,Date.now(),routes);syncBuses();map.triggerRepaint();}).catch(()=>{if(!disposed){document.querySelector('#overall-status')!.textContent='Vehicle updates unavailable';}}));
  jobs.push(get('/api/v1/health').then(h=>{if(disposed)return;feeds=h.data;const live=feeds.filter(f=>f.state==='live').length;document.querySelector('#overall-status')!.textContent=live?`${live} connected feeds`:'Live feeds not connected';document.querySelector('.status-dot')!.classList.toggle('live',live>0);for(const f of feeds){const el=document.querySelector(`#count-${f.id}`);if(el)el.textContent=f.state==='unavailable'?'—':String(f.count);}const traffic=feeds.find(f=>f.id==='traffic');if(!traffic?.message.includes('Tiles load'))document.querySelector('#traffic-availability')!.textContent=traffic?.state??'unavailable';}).catch(()=>{}));
  if(Date.now()-slowUpdated>=CADENCE.roadworks){slowUpdated=Date.now();
   jobs.push(get('/api/v1/road-events').then(e=>{if(disposed)return;events=e.data;furniture.setEvents(events);(map.getSource('road-events') as GeoJSONSource).setData({type:'FeatureCollection',features:events.map(e=>({type:'Feature',geometry:e.geometry,properties:{id:e.id,kind:e.kind}}))});syncMarkers();}).catch(()=>{}));
   if(feeds.some(f=>f.id==='traffic'&&f.state==='live'))jobs.push(get('/api/v1/traffic').then(t=>{if(disposed)return;roadTraffic=t.data;(map.getSource('traffic') as GeoJSONSource).setData({type:'FeatureCollection',features:roadTraffic.map(t=>({type:'Feature',geometry:{type:'LineString',coordinates:t.coordinates},properties:{id:t.id,ratio:t.currentSpeed/t.freeFlowSpeed}}))});}).catch(()=>{}));
  }
  await Promise.allSettled(jobs);refreshing=false;if(!disposed&&!document.hidden)timer=setTimeout(refresh,CADENCE.buses);
 };
 const visibility=()=>{clearTimeout(timer);if(!document.hidden){void refresh();map.triggerRepaint();}};document.addEventListener('visibilitychange',visibility);
 const routeSelection=(e:Event)=>{selectedBusRoute=(e as CustomEvent<string>).detail;syncBuses();map.triggerRepaint();};document.addEventListener('reading-bus-route',routeSelection);
 map.on('moveend',syncMarkers);syncMarkers();void refresh();vehicleTimer=setInterval(()=>{tracker.prune();if(!document.hidden)syncBuses();if(tracker.tracks.size&&!document.hidden)map.triggerRepaint();},1000);
 const unregister=registerMapTools({places:features.places,setLayer,getState:()=>({layers:{...state},feeds,center:map.getCenter().toArray(),zoom:map.getZoom(),rendering:{fps:Math.round(scene.fps),chunks:scene.chunks.size,failedChunks:scene.failed.size,geometries:scene.renderer.info.memory.geometries,drawCalls:scene.renderer.info.render.calls,trackedVehicles:tracker.tracks.size,visibleVehicles:poses.length,busInstances:vehicles.parts.find(p=>p.kind==='bus')?.mesh.count??0}}),navigate:async p=>{map.flyTo({center:p,zoom:16.8,pitch:58});await new Promise<void>(r=>map.once('moveend',()=>r()));}});
 map.on('remove',()=>{disposed=true;document.removeEventListener('visibilitychange',visibility);document.removeEventListener('reading-bus-route',routeSelection);clearTimeout(timer);clearInterval(vehicleTimer);markers.forEach(m=>m.remove());markers.clear();unregister();});
}
