import express from'express';import compression from'compression';import{readFile,mkdir}from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';import type{VehicleObservation,LngLat,TrafficSegment,FeedStatus}from'../shared/types';import{fetchBuses}from'./providers/buses';import{matchBusRoute,type BusNetwork}from'./route-matcher';import{RailNetwork,STATIONS}from'./rail-network';import{fetchRailBoard,estimateBoard}from'./providers/trains';import{parseStreetManager}from'./providers/roadworks';import{validateSns,confirmSns}from'./providers/sns';import{fetchTraffic}from'./providers/traffic';import{RoadEventStore}from'./store';import{Poller}from'./poller';
export async function createApp(options:{env?:NodeJS.ProcessEnv;database?:string;startPolling?:boolean}={}){const env=options.env??process.env;await mkdir('var',{recursive:true});const store=new RoadEventStore(options.database??'var/roadworks.sqlite');const app=express();app.disable('x-powered-by');app.use(compression());app.use((_req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');next();});
 const network:BusNetwork=JSON.parse(await readFile('public/data/bus-network.json','utf8'));const rail=await RailNetwork.load();let busRoutes:Record<string,LngLat[]>={},railRoutes:Record<string,LngLat[]>={};
 const buses=new Poller<VehicleObservation>('buses','Buses',15000,env.BODS_API_KEY?async()=>{const rows=await fetchBuses(env.BODS_API_KEY!);const next:Record<string,LngLat[]>={};const out=rows.map(o=>{const m=matchBusRoute(o,network);if(m.route&&m.observation.tripId)next[m.observation.tripId]=m.route;return m.observation;});busRoutes=next;return out;}:undefined,'BODS registration required');
 const trains=new Poller<VehicleObservation>('trains','Trains',30000,env.DARWIN_TOKEN?async()=>{const stationList=Object.keys(STATIONS);const results=await Promise.allSettled(stationList.map(s=>fetchRailBoard(env.DARWIN_TOKEN!,s)));const map=new Map<string,VehicleObservation>(),next:Record<string,LngLat[]>={};let successes=0;results.forEach((r,i)=>{if(r.status==='fulfilled'){successes++;const data=estimateBoard(r.value,stationList[i],rail);for(const o of data.observations){const old=map.get(o.id);if(!old||Date.parse(o.observedAt)>Date.parse(old.observedAt))map.set(o.id,o);}Object.assign(next,data.routes);}});if(!successes)throw Error('Rail feed unavailable');railRoutes=next;return[...map.values()];}:undefined,'National Rail token required; positions will be estimates');
 const traffic=new Poller<TrafficSegment>('traffic','Road traffic',60000,env.TRAFFIC_FEED_URL?()=>fetchTraffic(env.TRAFFIC_FEED_URL!,env.TRAFFIC_FEED_TOKEN):undefined,'No verified traffic feed configured');
 let lastRoadDelivery:string|undefined=store.lastUpdate();let subscriptionConfirmed=false;
 const snapshot=(data:unknown[])=>({version:1,generatedAt:new Date().toISOString(),data});
 app.get('/api/v1/vehicles',(_req,res)=>res.json(snapshot([...buses.data,...trains.data].filter(v=>Date.now()-Date.parse(v.observedAt)<300000))));
 app.get('/api/v1/vehicle-routes',(_req,res)=>res.json({version:1,routes:{...busRoutes,...railRoutes}}));
 app.get('/api/v1/road-events',(_req,res)=>res.json(snapshot(store.active())));
 app.get('/api/v1/traffic',(_req,res)=>res.json(snapshot(traffic.data.filter(t=>Date.now()-Date.parse(t.observedAt)<300000))));
 const health=()=>{const roads:FeedStatus={id:'roadworks',label:'Roadworks & closures',state:env.STREET_MANAGER_ENABLED==='true'&&subscriptionConfirmed?'live':lastRoadDelivery?'stale':'unavailable',message:env.STREET_MANAGER_ENABLED==='true'&&subscriptionConfirmed?'Receiving event notifications; coverage begins at subscription':lastRoadDelivery?'Stored events available; receiver connection unverified':'Street Manager subscription and public HTTPS receiver required',lastSuccess:lastRoadDelivery,count:store.active().length,intervalMs:0};return[buses.health(),trains.health(),roads,traffic.health()];};
 app.get('/api/v1/health',(_req,res)=>res.json(snapshot(health())));
 app.post('/api/v1/ingest/street-manager',express.text({type:()=>true,limit:'1mb'}),async(req,res)=>{if(env.STREET_MANAGER_ENABLED!=='true'){res.status(503).json({error:'Receiver disabled'});return;}try{const m=JSON.parse(req.body);await validateSns(m);if(store.seen(m.MessageId)){res.json({duplicate:true});return;}if(m.Type==='SubscriptionConfirmation'){await confirmSns(m);subscriptionConfirmed=true;}else{const event=parseStreetManager(JSON.parse(m.Message));if(event)store.upsert(event);lastRoadDelivery=new Date().toISOString();subscriptionConfirmed=true;}store.record(m.MessageId);res.json({accepted:true});}catch{res.status(400).json({error:'Invalid or unverified Street Manager message'});}});
 app.use('/api',(_req,res)=>res.status(404).json({error:'Unknown API endpoint'}));
 app.use('/data',express.static(path.resolve('public/data'),{maxAge:'1h',setHeaders:(res,p)=>{if(p.endsWith('.pbf'))res.setHeader('Content-Type','application/x-protobuf');}}));app.use(express.static(path.resolve('dist')));app.get('/',(_req,res)=>res.sendFile(path.resolve('dist/index.html')));
 if(options.startPolling!==false){buses.start();trains.start();traffic.start();}const close=()=>{buses.stop();trains.stop();traffic.stop();store.close();};return{app,close,store,health};
}
