import{distance,nearestOnLine}from'../shared/geo';import type{LngLat}from'../shared/types';
export const STATIONS:Record<string,LngLat>={RDG:[-.9723182,51.4592197],RDW:[-.9907169,51.4546483],TLH:[-1.0296647,51.4716513],TWY:[-.8631386,51.47539],WTI:[-.8918298,51.4367674],WNS:[-.8779199,51.4307527],EAR:[-.9177114,51.4410298],RGP:[-1.0013637,51.4265936],THE:[-1.074364,51.4333628],WKM:[-.8429813,51.4119036],WGV:[-.8766558,51.4985546]};
type Node={p:LngLat;edges:{id:string;cost:number}[]};
export class RailNetwork{nodes=new Map<string,Node>();cache=new Map<string,LngLat[]|null>();
 constructor(features:any[]){for(const f of features){if(f.properties?.railway!=='rail'||f.properties?.service||f.geometry?.type!=='LineString')continue;const coords=f.geometry.coordinates as LngLat[];for(let i=0;i<coords.length;i++){const id=coords[i].join(',');if(!this.nodes.has(id))this.nodes.set(id,{p:coords[i],edges:[]});if(i){const prev=coords[i-1].join(','),cost=distance(coords[i-1],coords[i]);this.nodes.get(prev)!.edges.push({id,cost});this.nodes.get(id)!.edges.push({id:prev,cost});}}}}
 nearest(p:LngLat){let id='',d=Infinity;for(const[k,n]of this.nodes){const dd=distance(n.p,p);if(dd<d){d=dd;id=k;}}return d<400?id:null;}
 route(a:string,b:string){const key=`${a}:${b}`;if(this.cache.has(key))return this.cache.get(key)!;const start=STATIONS[a]&&this.nearest(STATIONS[a]),end=STATIONS[b]&&this.nearest(STATIONS[b]);if(!start||!end)return null;const costs=new Map([[start,0]]),prev=new Map<string,string>(),queue:[string,number][]=[[start,0]],done=new Set<string>();while(queue.length){queue.sort((a,b)=>b[1]-a[1]);const[id,cost]=queue.pop()!;if(done.has(id))continue;done.add(id);if(id===end)break;for(const e of this.nodes.get(id)!.edges){const next=cost+e.cost;if(next<(costs.get(e.id)??Infinity)){costs.set(e.id,next);prev.set(e.id,id);queue.push([e.id,next]);}}}if(!costs.has(end)){this.cache.set(key,null);return null;}const path:LngLat[]=[];let id=end;while(id!==start){path.push(this.nodes.get(id)!.p);id=prev.get(id)!;}path.push(this.nodes.get(start)!.p);path.reverse();this.cache.set(key,path);return path;}
 static async load(){const {readFile}=await import('node:fs/promises');const geo=JSON.parse(await readFile('public/data/railways.json','utf8'));return new RailNetwork(geo.features);}
}
