import * as T from'three';import{MercatorCoordinate,type Map as MLMap,type CustomLayerInterface,type CustomRenderMethodInput}from'maplibre-gl';import{ORIGIN}from'../../shared/config';import{intersects}from'../../shared/geo';import type{Bounds,GeographyManifest}from'../../shared/types';import{buildingMaterial}from'./materials';import{createLandmarks}from'./landmarks';import type{MeshData}from'./buildings.worker';
import {georeferencedLandmarks} from './georeferenced-landmarks';
import type {LandmarkComponent} from '../../shared/landmark-components';
export class ReadingScene implements CustomLayerInterface{
 id='reading-3d';type='custom' as const;renderingMode='3d' as const;scene=new T.Scene();camera=new T.Camera();renderer!:T.WebGLRenderer;map!:MLMap;buildings=new T.Group();landmarks=createLandmarks();extras=new T.Group();ambient=new T.AmbientLight('#ffffff',1.6);sun=new T.DirectionalLight('#fff1d8',2.0);worker:Worker;chunks=new Map<string,T.Group>();pending=new Set<string>();failed=new Set<string>();wanted=new Set<string>();wallMaterial=buildingMaterial();roofMaterial=new T.MeshLambertMaterial({vertexColors:true,side:T.DoubleSide});enabled=true;disposed=false;animate?:()=>boolean;last=0;fps=60;frames=0;sample=0;maxChunks=80;onStats?:(stats:{fps:number;drawCalls:number;chunks:number;geometries:number})=>void;
 constructor(public manifest:GeographyManifest,components:LandmarkComponent[]=[]){this.landmarks.add(georeferencedLandmarks(components));this.worker=new Worker(new URL('./buildings.worker.ts',import.meta.url),{type:'module'});this.worker.onmessage=({data})=>{this.pending.delete(data.id);if(data.error)this.failed.add(data.id);if(!this.wanted.has(data.id)||data.error||this.disposed){this.loadNext();return;}const g=new T.Group();for(const key of ['walls','roofs']as const){const d:MeshData=data[key];const geom=new T.BufferGeometry();geom.setAttribute('position',new T.BufferAttribute(d.position,3));geom.setAttribute('uv',new T.BufferAttribute(d.uv,2));geom.setAttribute('color',new T.BufferAttribute(d.color,3));geom.computeVertexNormals();geom.computeBoundingSphere();g.add(new T.Mesh(geom,key==='walls'?this.wallMaterial:this.roofMaterial));}this.chunks.set(data.id,g);this.buildings.add(g);this.map.triggerRepaint();this.loadNext();};}
 onAdd(map:MLMap,gl:WebGLRenderingContext|WebGL2RenderingContext){this.map=map;this.renderer=new T.WebGLRenderer({canvas:map.getCanvas(),context:gl as WebGL2RenderingContext});this.renderer.autoClear=false;this.renderer.outputColorSpace=T.SRGBColorSpace;this.scene.add(this.ambient);this.sun.position.set(-1000,-1600,2400);this.scene.add(this.sun);this.scene.add(this.buildings,this.landmarks,this.extras);map.on('moveend',this.updateChunks);this.updateChunks();}
 updateChunks=()=>{if(this.disposed)return;const b=this.map.getBounds(),bounds:Bounds=[b.getWest(),b.getSouth(),b.getEast(),b.getNorth()],c=this.map.getCenter();const eligible=this.map.getZoom()>=14?this.manifest.chunks.filter(ch=>intersects(ch.bounds,bounds)).sort((a,b)=>Math.hypot((a.bounds[0]+a.bounds[2])/2-c.lng,(a.bounds[1]+a.bounds[3])/2-c.lat)-Math.hypot((b.bounds[0]+b.bounds[2])/2-c.lng,(b.bounds[1]+b.bounds[3])/2-c.lat)).slice(0,this.maxChunks):[];this.wanted=new Set(eligible.map(c=>c.id));for(const[id,g]of this.chunks)if(!this.wanted.has(id)){this.buildings.remove(g);g.traverse(o=>{if(o instanceof T.Mesh)o.geometry.dispose();});this.chunks.delete(id);}this.loadNext();};
 loadNext(){if(this.disposed)return;for(const id of this.wanted){if(this.pending.size>=3)return;if(this.pending.has(id)||this.chunks.has(id)||this.failed.has(id))continue;const chunk=this.manifest.chunks.find(c=>c.id===id)!;this.pending.add(id);this.worker.postMessage({id,url:chunk.url});}}
 render(_gl:WebGLRenderingContext|WebGL2RenderingContext,args:CustomRenderMethodInput){const origin=MercatorCoordinate.fromLngLat(ORIGIN),s=origin.meterInMercatorCoordinateUnits();const model=new T.Matrix4().makeTranslation(origin.x,origin.y,0).scale(new T.Vector3(s,-s,s));this.camera.projectionMatrix.fromArray(args.defaultProjectionData.mainMatrix).multiply(model);this.camera.projectionMatrixInverse.copy(this.camera.projectionMatrix).invert();this.buildings.visible=this.enabled&&this.map.getZoom()>=14;this.landmarks.visible=this.enabled;const moving=this.animate?.()??false;this.renderer.resetState();this.renderer.render(this.scene,this.camera);const now=performance.now();if(this.last&&now-this.last<250){this.frames++;this.sample+=now-this.last;if(this.sample>1500){this.fps=this.frames*1000/this.sample;this.frames=0;this.sample=0;this.onStats?.({fps:this.fps,drawCalls:this.renderer.info.render.calls,chunks:this.chunks.size,geometries:this.renderer.info.memory.geometries});}}this.last=now;if(moving&&!document.hidden)this.map.triggerRepaint();}
 setEnabled(value:boolean){this.enabled=value;this.map.triggerRepaint();}
 onRemove(){this.disposed=true;this.worker.terminate();this.map.off('moveend',this.updateChunks);const geoms=new Set<T.BufferGeometry>(),mats=new Set<T.Material>();this.scene.traverse(o=>{if(o instanceof T.Mesh){geoms.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])mats.add(m);}});geoms.forEach(g=>g.dispose());mats.forEach(m=>{const mm=m as T.MeshLambertMaterial;mm.map?.dispose();m.dispose();});this.renderer.dispose();this.chunks.clear();}
}
