import{XMLParser}from'fast-xml-parser';import type{VehicleObservation}from'../../shared/types';import{validPosition,inBounds}from'../../shared/geo';import{freshObservation}from'../../shared/feed-policy';import{fetchVehicleTrips,type VehicleTrip}from'./gtfs-rt';
const list=(x:any)=>x==null?[]:Array.isArray(x)?x:[x];const value=(x:any)=>x&&typeof x==='object'?x['#text']:x;
export function parseSiri(input:string|object):VehicleObservation[]{const root=typeof input==='string'?new XMLParser({removeNSPrefix:true,parseTagValue:false}).parse(input):input;const delivery=(root as any).Siri?.ServiceDelivery??(root as any).ServiceDelivery??root;const out:VehicleObservation[]=[];
 for(const d of list((delivery as any).VehicleMonitoringDelivery))for(const a of list(d.VehicleActivity)){const j=a.MonitoredVehicleJourney;if(!j)continue;const position:[number,number]=[Number(value(j.VehicleLocation?.Longitude)),Number(value(j.VehicleLocation?.Latitude))];const observedAt=String(value(a.RecordedAtTime)??'');if(!validPosition(position)||!Number.isFinite(Date.parse(observedAt)))continue;const id=value(j.VehicleRef);if(!id)continue;out.push({id:`bods:${value(j.OperatorRef)??'unknown'}:${id}`,kind:'bus',position,observedAt,operatorId:String(value(j.OperatorRef)??''),bearing:j.Bearing==null?undefined:Number(value(j.Bearing)),label:String(value(j.PublishedLineName)??value(j.LineRef)??'Bus'),destination:String(value(j.DestinationName)??''),routeId:String(value(j.LineRef)??''),tripId:String(value(j.FramedVehicleJourneyRef?.DatedVehicleJourneyRef)??value(j.VehicleJourneyRef)??''),status:'observed',source:'Bus Open Data Service',sourceUrl:'https://www.bus-data.dft.gov.uk/'});}
 return out;
}
export async function fetchBuses(key:string){const tripsRequest=fetchVehicleTrips(key).catch(()=>undefined);const url=new URL('https://data.bus-data.dft.gov.uk/api/v1/datafeed/');url.searchParams.set('api_key',key);url.searchParams.set('boundingBox','-1.09,51.38,-0.83,51.51');const r=await fetch(url,{headers:{'User-Agent':'MiniReading3D/1.0 (+https://github.com/Zagitalc/mini-reading-3d)','Accept':'text/xml'},redirect:'manual',signal:AbortSignal.timeout(12000)});if(!r.ok){const body=await r.text(),type=r.headers.get('content-type')??'';const hint=/block access from your country|geographic restriction|geo.?blocked/i.test(body)?'geographic restriction':/(invalid|incorrect|missing|expired).{0,30}(api.?key|credential)|(api.?key|credential).{0,30}(invalid|incorrect|missing|expired)/i.test(body)?'credential rejected':/request could not be satisfied|request blocked|cloudfront|access denied/i.test(body)?'gateway rejection':type.includes('html')?'HTML response':type.includes('json')?'JSON response':'';throw Error(`Bus provider returned HTTP ${r.status}${hint?` (${hint})`:''}`);}const text=await r.text();if(!text.includes('VehicleMonitoringDelivery')&&!text.includes('ServiceDelivery'))throw Error('Bus provider returned an unrecognised response');const buses=parseSiri(text).filter(o=>freshObservation(o)&&inBounds(o.position));
 // SIRI-VM from Reading Buses carries no reference to a timetabled journey; the GTFS-RT feed names the bundled trip.
 // It is optional: without it buses still show, and stops keep scheduled times only.
 const trips=await tripsRequest;return trips?withTimetableTrips(buses,trips):buses;}
/** Attach the GTFS trip a vehicle is running, joining the two BODS feeds on the vehicle reference (a registration for Reading Buses). */
export function withTimetableTrips(buses:VehicleObservation[],trips:VehicleTrip[]){
 const byVehicle=new Map<string,VehicleTrip|null>();
 // A vehicle listed twice with different trips is ambiguous, so it gets none.
 for(const t of trips){const key=t.vehicleId.replace(/\s+/g,'').toUpperCase(),old=byVehicle.get(key);byVehicle.set(key,old===undefined||old?.tripId===t.tripId?t:null);}
 return buses.map(o=>{const trip=byVehicle.get(o.id.split(':').slice(2).join(':').replace(/\s+/g,'').toUpperCase());
  // Positions from the two feeds must describe the same moment, or the trip could belong to an earlier journey.
  if(!trip||trip.timestamp!==undefined&&Math.abs(trip.timestamp-Date.parse(o.observedAt))>180_000)return o;
  return {...o,timetableTripId:trip.tripId};});
}
