import proj4 from'proj4';import type{RoadEvent,LngLat}from'../../shared/types';import{geometryIntersects,inBounds,validPosition}from'../../shared/geo';
proj4.defs('EPSG:27700','+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.060,0.1502,0.2470,0.8421,-20.4894 +units=m +no_defs');
export function parseWkt(wkt:string):RoadEvent['geometry']|null{const match=wkt?.match(/^\s*(POINT|LINESTRING)\s*\(([^)]+)\)\s*$/i);if(!match)return null;const points=match[2].split(',').map(s=>s.trim().split(/\s+/).map(Number)).map(p=>proj4('EPSG:27700','EPSG:4326',p)as LngLat);if(points.some(p=>!validPosition(p)))return null;if(match[1].toUpperCase()==='POINT')return points.length===1?{type:'Point',coordinates:points[0]}:null;return points.length>=2?{type:'LineString',coordinates:points}:null;}
const date=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v))?v:undefined;
export function parseStreetManager(payload:any):RoadEvent|null{const p=payload.object_data;if(!p||!['PERMIT','ACTIVITY'].includes(String(payload.object_type).toUpperCase()))return null;const geometry=parseWkt(String(p.works_location_coordinates??p.activity_coordinates??''));if(!geometry)return null;if(geometry.type==='Point'?!inBounds(geometry.coordinates):!geometryIntersects(geometry.coordinates))return null;
 const kind=String(payload.event_type??'').toLowerCase().replace(/_/g,'-');const management=String(p.current_traffic_management_type_ref??p.current_traffic_management_type??p.traffic_management_type_ref??p.traffic_management_type??'');
 let status:RoadEvent['status']='planned';if(/cancel|revok|refus/.test(kind)||String(p.cancelled).toLowerCase()==='yes')status='cancelled';else if(kind==='work-stop'||p.actual_end_date_time)status='completed';else if(kind==='work-start'||p.work_status_ref==='in_progress')status='active';
 if(kind==='work-stop-reverted')status='active';if(kind==='work-start-reverted')status='planned';
 const observedAt=date(payload.event_time);if(!observedAt)return null;const id=String(p.work_reference_number??p.activity_reference_number??payload.object_reference??'');if(!id)return null;
 return{id:`streetmanager:${id}`,title:String(p.street_name??p.activity_name??'Roadworks'),description:String(p.activity_type_details??p.activity_name??p.activity_type??p.work_category??'Roadworks'),organisation:String(p.promoter_organisation??p.highway_authority??'Unknown'),geometry,kind:/road[_ ]closure/i.test(management)?'closure':'works',status,plannedStart:date(p.proposed_start_date??p.start_date),plannedEnd:date(p.proposed_end_date??p.end_date),actualStart:date(p.actual_start_date_time),actualEnd:date(p.actual_end_date_time),observedAt,source:'DfT Street Manager',sourceUrl:'https://www.gov.uk/guidance/find-and-use-roadworks-data',version:Number(payload.version)||1,trafficManagement:management.replaceAll('_',' '),datePrecision:'date'};
}
