import './style.css';import * as maplibregl from'maplibre-gl';import{shell,detail,escape,toast}from'./ui/shell';import{BOUNDS,INITIAL_VIEW,LANDMARKS}from'../shared/config';import type{GeographyManifest,StaticFeatures,FeedStatus}from'../shared/types';import{mapStyle}from'./map/style';import{ReadingScene}from'./scene/layer';
import mapWorkerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
maplibregl.setWorkerUrl(mapWorkerUrl);
shell();
async function start(){const [manifest,features]:[GeographyManifest,StaticFeatures]=await Promise.all(['/data/manifest.json','/data/features.json'].map(async u=>{const r=await fetch(u);if(!r.ok)throw Error('Local geography is missing. Run npm run data:build.');return r.json();}))as any;
 const map=new maplibregl.Map({container:'map',style:mapStyle(),...INITIAL_VIEW,maxBounds:[[BOUNDS[0],BOUNDS[1]],[BOUNDS[2],BOUNDS[3]]],minZoom:11,maxZoom:19,maxPitch:70,canvasContextAttributes:{antialias:true},renderWorldCopies:false});
 map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'top-right');map.addControl(new maplibregl.ScaleControl({unit:'metric'}),'bottom-left');
 const scene=new ReadingScene(manifest);let orbit=false,frame=0;const stopOrbit=()=>{orbit=false;cancelAnimationFrame(frame);document.querySelector('#orbit-view')!.setAttribute('aria-pressed','false');};map.on('dragstart',stopOrbit);
 map.on('load',async()=>{map.addLayer(scene,'road-labels');document.querySelector<HTMLElement>('#loading')!.hidden=true;document.querySelector('#geography-status')!.textContent=`${manifest.stats.buildings.toLocaleString()} real building footprints`;document.querySelector('#overall-status')!.textContent='Live feeds not connected';
  const {connectLayers}=await import('./map/live-layers');await connectLayers(map,scene,features,manifest);
 });
 map.on('error',e=>{console.error(e.error);document.querySelector('#geography-status')!.textContent='Some map assets could not load';});const loadTimeout=setTimeout(()=>{const el=document.querySelector<HTMLElement>('#loading');if(el&&!el.hidden){el.innerHTML='<strong>The map is taking longer than expected</strong><span>Check the local server, then try reloading.</span><button onclick="location.reload()">Reload map</button>';}},20000);map.once('load',()=>clearTimeout(loadTimeout));
 document.querySelector('#home-view')!.addEventListener('click',()=>{stopOrbit();map.flyTo({...INITIAL_VIEW,duration:1600});document.querySelector('.view-caption .eyebrow')!.textContent='READING STATION';});document.querySelector('#overview')!.addEventListener('click',()=>{stopOrbit();map.fitBounds([[BOUNDS[0],BOUNDS[1]],[BOUNDS[2],BOUNDS[3]]],{padding:innerWidth>680?{top:125,left:330,right:80,bottom:130}:60,pitch:30,bearing:0,duration:1500});});document.querySelector('#tilt-view')!.addEventListener('click',()=>{map.easeTo({pitch:map.getPitch()>10?0:58,duration:800});});document.querySelector('#orbit-view')!.addEventListener('click',()=>{orbit=!orbit;document.querySelector('#orbit-view')!.setAttribute('aria-pressed',String(orbit));let last=performance.now();const step=(now:number)=>{if(!orbit)return;map.setBearing(map.getBearing()+(now-last)*.004);last=now;frame=requestAnimationFrame(step);};if(orbit)frame=requestAnimationFrame(step);});
 const landmarkButtons=document.querySelector('#landmark-buttons')!;for(const l of LANDMARKS){const b=document.createElement('button');b.textContent=l.id==='station'?'↗ Station':l.id==='university'?'University':l.id==='town-hall'?'Town Hall':l.name.replace('Reading ','');b.addEventListener('click',()=>{stopOrbit();map.flyTo({center:l.position,zoom:17,pitch:60,duration:1800});document.querySelector('.view-caption .eyebrow')!.textContent=l.name.toUpperCase();});landmarkButtons.append(b);const el=document.createElement('button');el.className='landmark-pin';el.setAttribute('aria-label',l.name);el.innerHTML=`${l.id==='station'?'▥':'◇'}<span class="pin-label">${escape(l.name)}</span>`;el.addEventListener('click',()=>{detail(`<span class="pill">${escape(l.kind)}</span><h2>${escape(l.name)}</h2><p>A stylised miniature at its geographic location. Architecture and textures are illustrative; surrounding footprints come from OpenStreetMap.</p><button class="status-button" id="focus-landmark">Take a closer look ↗</button>`);document.querySelector('#focus-landmark')!.addEventListener('click',()=>map.flyTo({center:l.position,zoom:17.7,pitch:60}));});new maplibregl.Marker({element:el}).setLngLat(l.position).addTo(map);}
 const search=document.querySelector<HTMLInputElement>('#search')!,results=document.querySelector<HTMLElement>('#search-results')!;search.addEventListener('input',()=>{results.replaceChildren();const q=search.value.trim().toLowerCase();results.hidden=!q;if(!q)return;const matches=features.places.filter(p=>p.name.toLowerCase().includes(q)).slice(0,8);if(!matches.length)results.textContent='No local places found.';for(const p of matches){const b=document.createElement('button');b.innerHTML=`${escape(p.name)}<small>${escape(p.kind)}</small>`;b.addEventListener('click',()=>{stopOrbit();map.flyTo({center:p.position,zoom:16,pitch:58});results.hidden=true;search.value=p.name;document.querySelector('.view-caption .eyebrow')!.textContent=p.name.toUpperCase();});results.append(b);}});
 map.on('moveend',()=>{const c=map.getCenter();document.querySelector('#view-coordinates')!.textContent=`${c.lat.toFixed(4)}° N · ${Math.abs(c.lng).toFixed(4)}° W`;});
 window.addEventListener('pagehide',()=>{stopOrbit();map.remove();},{once:true});
}
start().catch(error=>{const loading=document.querySelector('#loading')!;loading.innerHTML='<strong>Reading could not load</strong><span></span><button onclick="location.reload()">Try again</button>';loading.querySelector('span')!.textContent=error.message;console.error(error);});
