import './style.css';import{currentMode}from'./ui/modes';import * as maplibregl from'maplibre-gl';import{shell,detail,escape,toast}from'./ui/shell';import{storyHtml}from'./ui/landmark-story';import{BOUNDS,INITIAL_VIEW,LANDMARKS}from'../shared/config';import type{GeographyManifest,StaticFeatures,FeedStatus}from'../shared/types';import{mapStyle,followColourScheme}from'./map/style';import{ReadingScene}from'./scene/layer';import{connectShare,linkedCamera,onLinked,setSelection}from'./ui/share';import{connectSearch,registerSearch,MAX_HITS}from'./ui/search';import{connectSummary,publishFact}from'./ui/summary';import{rank}from'../shared/search';import{distance}from'../shared/geo';
import mapWorkerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
maplibregl.setWorkerUrl(mapWorkerUrl);
shell();connectSummary();
async function start(){const [manifest,features]:[GeographyManifest,StaticFeatures]=await Promise.all(['/data/manifest.json','/data/features.json'].map(async u=>{const r=await fetch(u);if(!r.ok)throw Error('Local geography is missing. Run npm run data:build.');return r.json();}))as any;
 const componentResponse=await fetch('/data/landmark-components.json');if(!componentResponse.ok)throw Error('Landmark geometry unavailable');const componentData=await componentResponse.json();
 const shared=linkedCamera(),map=new maplibregl.Map({container:'map',style:mapStyle(undefined,currentMode()),...(shared??INITIAL_VIEW),maxBounds:[[BOUNDS[0],BOUNDS[1]],[BOUNDS[2],BOUNDS[3]]],minZoom:11,maxZoom:19,maxPitch:70,canvasContextAttributes:{antialias:true},renderWorldCopies:false});
 map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'top-right');map.addControl(new maplibregl.ScaleControl({unit:'metric'}),'bottom-left');connectShare(map,toast);if(shared)document.querySelector('.view-caption .eyebrow')!.textContent='SHARED VIEW';
 const scene=new ReadingScene(manifest,componentData.components);let orbit=false,frame=0;const stopOrbit=()=>{orbit=false;cancelAnimationFrame(frame);document.querySelector('#orbit-view')!.setAttribute('aria-pressed','false');};map.on('dragstart',stopOrbit);
 map.on('load',async()=>{map.addLayer(scene,'road-labels');document.querySelector<HTMLElement>('#loading')!.hidden=true;document.querySelector('#geography-status')!.textContent=`${manifest.stats.buildings.toLocaleString()} real building footprints`;document.querySelector('#overall-status')!.textContent='Live feeds not connected';
  const {connectLayers}=await import('./map/live-layers');await connectLayers(map,scene,features,manifest);const {connectRouteLayers}=await import('./map/route-layers');await connectRouteLayers(map);const {connectStopLayers}=await import('./map/stop-layers');await connectStopLayers(map);const {connectServiceExplorer}=await import('./map/service-explorer');await connectServiceExplorer();const {connectScenarios}=await import('./map/scenario-panel');await connectScenarios(map);const {connectDirectFinder}=await import('./map/direct-finder-panel');await connectDirectFinder(map);const {connectHistoryPanel}=await import('./map/history-panel');connectHistoryPanel();const {connectEnvironment}=await import('./map/environment-layers');await connectEnvironment(map,scene);const {connectPlaces}=await import('./map/places-layer');connectPlaces(map);
  onLinked('landmark',async(id,fly)=>{const l=LANDMARKS.find(l=>l.id===id),open=landmarkOpeners.get(id);if(!l||!open)return false;if(fly){stopOrbit();map.flyTo({center:l.position,zoom:17.7,pitch:60});}await open();return true;});
 });
 followColourScheme(map);map.on('error',e=>{if((e as {sourceId?:string}).sourceId==='tomtom-flow')return;console.error(e.error);document.querySelector('#geography-status')!.textContent='Some map assets could not load';});const loadTimeout=setTimeout(()=>{const el=document.querySelector<HTMLElement>('#loading');if(el&&!el.hidden){el.innerHTML='<strong>The map is taking longer than expected</strong><span>Check the local server, then try reloading.</span><button onclick="location.reload()">Reload map</button>';}},20000);map.once('load',()=>clearTimeout(loadTimeout));
 document.querySelector('#home-view')!.addEventListener('click',()=>{stopOrbit();map.flyTo({...INITIAL_VIEW,duration:1600});document.querySelector('.view-caption .eyebrow')!.textContent='READING STATION';});document.querySelector('#overview')!.addEventListener('click',()=>{stopOrbit();map.fitBounds([[BOUNDS[0],BOUNDS[1]],[BOUNDS[2],BOUNDS[3]]],{padding:innerWidth>680?{top:125,left:330,right:80,bottom:130}:60,pitch:30,bearing:0,duration:1500});});document.querySelector('#tilt-view')!.addEventListener('click',()=>{map.easeTo({pitch:map.getPitch()>10?0:58,duration:800});});document.querySelector('#orbit-view')!.addEventListener('click',()=>{orbit=!orbit;document.querySelector('#orbit-view')!.setAttribute('aria-pressed',String(orbit));let last=performance.now();const step=(now:number)=>{if(!orbit)return;map.setBearing(map.getBearing()+(now-last)*.004);last=now;frame=requestAnimationFrame(step);};if(orbit)frame=requestAnimationFrame(step);});
 const landmarkButtons=document.querySelector('#landmark-buttons')!,landmarkOpeners=new Map<string,()=>Promise<void>>();for(const l of LANDMARKS){const b=document.createElement('button');b.textContent=l.id==='station'?'↗ Station':l.id==='university'?'University':l.id==='town-hall'?'Town Hall':l.id==='stadium'?'Stadium':l.name.replace('Reading ','');b.addEventListener('click',()=>{stopOrbit();map.flyTo({center:l.position,zoom:17,pitch:60,duration:1800});document.querySelector('.view-caption .eyebrow')!.textContent=l.name.toUpperCase();});landmarkButtons.append(b);const el=document.createElement('button');el.className='landmark-pin';el.setAttribute('aria-label',l.name);el.innerHTML=`${l.id==='station'?'▥':'◇'}<span class="pin-label">${escape(l.name)}</span>`;const openLandmark=async()=>{if(l.id==='station'){const {openStationBoard}=await import('./map/station-board');openStationBoard(()=>map.flyTo({center:l.position,zoom:17.7,pitch:60}));setSelection({kind:'landmark',id:l.id});return;}detail(`<span class="pill">${escape(l.kind)}</span><h2>${escape(l.name)}</h2><p>A stylised miniature at its geographic location. Architecture and textures are illustrative; surrounding footprints come from OpenStreetMap.</p><button class="status-button" id="focus-landmark">Take a closer look ↗</button>${storyHtml(l.id)}`);document.querySelector('#focus-landmark')!.addEventListener('click',()=>map.flyTo({center:l.position,zoom:17.7,pitch:60}));setSelection({kind:'landmark',id:l.id});};el.addEventListener('click',()=>void openLandmark());landmarkOpeners.set(l.id,openLandmark);new maplibregl.Marker({element:el}).setLngLat(l.position).addTo(map);}
 // Places and landmarks for the search box; every other layer registers its own results once its data has loaded.
 connectSearch();const caption=(name:string)=>{document.querySelector('.view-caption .eyebrow')!.textContent=name.toUpperCase();};
 const landmarkIds=new Set(LANDMARKS.map(l=>l.id)),places=features.places.filter(p=>!landmarkIds.has(p.id)),kindName=(k:string)=>(k[0]?.toUpperCase()??'')+k.slice(1).replace(/_/g,' ');
 registerSearch('place',q=>rank(places,q,p=>[p.name],p=>p.name,MAX_HITS).map(({item:p})=>({title:p.name,detail:kindName(p.kind),open:()=>{stopOrbit();map.flyTo({center:p.position,zoom:16,pitch:58});caption(p.name);}})));
 registerSearch('landmark',q=>rank(LANDMARKS,q,l=>[l.name,l.kind],l=>l.name,MAX_HITS).map(({item:l})=>({title:l.name,detail:l.id==='station'?'Live departures':l.kind,open:()=>{stopOrbit();map.flyTo({center:l.position,zoom:17.7,pitch:60});caption(l.name);void landmarkOpeners.get(l.id)?.();}})));
 const showCoordinates=()=>{const c=map.getCenter();document.querySelector('#view-coordinates')!.textContent=`${c.lat.toFixed(4)}° N · ${Math.abs(c.lng).toFixed(4)}° W`;
  // Explore card: the modelled landmark nearest the middle of the map.
  const nearest=LANDMARKS.map(l=>({name:l.name,metres:distance([c.lng,c.lat],l.position)})).sort((a,b)=>a.metres-b.metres)[0];publishFact('explore',{buildings:manifest.stats.buildings,landmarks:LANDMARKS.length,nearest});};map.on('moveend',showCoordinates);showCoordinates();
 window.addEventListener('pagehide',()=>{stopOrbit();map.remove();},{once:true});
}
start().catch(error=>{const loading=document.querySelector('#loading')!;loading.innerHTML='<strong>Reading could not load</strong><span></span><button onclick="location.reload()">Try again</button>';loading.querySelector('span')!.textContent=error.message;console.error(error);});
